Description: Video analytics via. TwelveLabs APIs

Resources:
  #
  # S3 Bucket
  #
  S3:
    Type: AWS::S3::Bucket

  #
  # DyanmoDB Tables
  #
  simpleChecksindexing:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'simple_checks_indexing'
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: 's3_path'
          KeyType: HASH   # partition key
  
  isPartofCampaign:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'is_part_of_campaign'
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: 's3_path'
          KeyType: HASH   # partition key

  isPartofCampaign:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'milk_mob'
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: 's3_path'
          KeyType: HASH   # partition key

  #
  # S3 Vector
  #
