Description: Video analytics via. TwelveLabs APIs

Resources:
  #
  # S3 Bucket
  #
  S3:
    Type: AWS::S3::Bucket

  #
  # DyanmoDB Tables
  #
  SimpleChecksIndexing:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: simple_checks_indexing
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: s3_path
          AttributeType: S # string attribute
      KeySchema:
        - AttributeName: s3_path
          KeyType: HASH # partition key
  
  IsPartofCampaign:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: is_part_of_campaign
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: s3_path
          AttributeType: S # string attribute
      KeySchema:
        - AttributeName: s3_path
          KeyType: HASH # partition key

  MilkMob:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: milk_mob
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: s3_path
          AttributeType: S # string attribute
      KeySchema:
        - AttributeName: s3_path
          KeyType: HASH # partition key

  #
  # S3 Vector
  #
  S3Vector:
    Type: AWS::S3Vectors::VectorBucket
    Properties:
      VectorBucketName: got-milk

  S3Index:
    Type: AWS::S3Vectors::Index
    Properties:
      IndexName: visual-video
      DataType: float32
      Dimension: 512     
      DistanceMetric: cosine
      VectorBucketArn: !GetAtt S3Vector.VectorBucketArn

  #
  # Lambda Function IAM role
  #
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        # Imporvement required - premissions need to be scoped down
        - PolicyName: Admin
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - '*'
                Resource: '*'
                
  #
  # Lambda Function #1 - simple_checks_indexing
  #
    DownloadJARsScriptLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: simple_checks_indexing
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.14
      Code:
        ZipFile: |
          import json
          import urllib.parse
          import boto3
          import os

          #from twelvelabs import TwelveLabs 
          #from twelvelabs.tasks import TasksRetrieveResponse
          
          def lambda_handler(event, context):
  
                # Return lambda response
                return {
                  'statusCode': 200,
                  'body': json.dumps('Lambda execution complete')
                }          
      Timeout: 300
      MemorySize: 1024
      EphemeralStorage: 
        Size: 1024
      Environment:
        Variables:
          API_KEY: ''
          INDEX_ID: ''
  
  #
  # Lambda Function #2 - is_part_of_campaign 
  #

  #
  # Lambda Function #3 - milk_mob
  #
  
